'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.85
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial NotInheritable Class MySettings
    Inherits System.Configuration.ApplicationSettingsBase
    
    Private Shared m_Value As MySettings
    
    Private Shared m_SyncObject As Object = New Object
    
    <System.Diagnostics.DebuggerNonUserCode()>  _
    Public Shared ReadOnly Property Value() As MySettings
        Get
            If (MySettings.m_Value Is Nothing) Then
                System.Threading.Monitor.Enter(MySettings.m_SyncObject)
                If (MySettings.m_Value Is Nothing) Then
                    Try 
                        MySettings.m_Value = New MySettings
                    Finally
                        System.Threading.Monitor.Exit(MySettings.m_SyncObject)
                    End Try
                End If
            End If
            Return MySettings.m_Value
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCode(),  _
     System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString),  _
     System.Configuration.ApplicationScopedSettingAttribute(),  _
     System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\Data.mdb;Persist Security Inf"& _ 
        "o=True")>  _
    Public ReadOnly Property Connection() As String
        Get
            Return CType(Me("Connection"),String)
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCode(),  _
     System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString),  _
     System.Configuration.ApplicationScopedSettingAttribute(),  _
     System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\Data\ReplikatVonData.mdb;Persist S"& _ 
        "ecurity Info=True")>  _
    Public ReadOnly Property Connection1() As String
        Get
            Return CType(Me("Connection1"),String)
        End Get
    End Property
End Class

Namespace My
    
    <Microsoft.VisualBasic.HideModuleName()>  _
    Public Module MySettingsProperty
        
        <System.Diagnostics.DebuggerNonUserCode()>  _
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Value
            End Get
        End Property
    End Module
End Namespace
