'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.85
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    Partial Class MyApplication
        Inherits System.Windows.Forms.WindowsFormsApplicationBase
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Sub New()
            MyBase.New(System.Windows.Forms.AuthenticationMode.Windows)
            Me.IsSingleInstance = true
            Me.EnableVisualStyles = true
            Me.ShutDownStyle = System.Windows.Forms.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = My.Forms.frmMain
        End Sub
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Protected Overrides Sub OnCreateSplashScreen()
            Me.SplashScreen = New Evolution_des_Lebens.frmSplashScreen
        End Sub
    End Class
End Namespace
