'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.85
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.IO
Imports System.Resources

Namespace My.Resources
    
    '''<summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    'This class was auto-generated by the Strongly Typed Resource Builder
    'class via a tool like ResGen or Visual Studio.NET.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    <Microsoft.VisualBasic.HideModuleName()>  _
    Module MyResources
        
        Private _resMgr As System.Resources.ResourceManager
        
        Private _resCulture As System.Globalization.CultureInfo
        
        '''<summary>
        '''   Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As System.Resources.ResourceManager
            Get
                If (_resMgr Is Nothing) Then
                    Dim temp As System.Resources.ResourceManager = New System.Resources.ResourceManager("Evolution_des_Lebens.MyResources", GetType(MyResources).Assembly)
                    _resMgr = temp
                End If
                Return _resMgr
            End Get
        End Property
        
        '''<summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        '''</summary>
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As System.Globalization.CultureInfo
            Get
                Return _resCulture
            End Get
            Set
                _resCulture = value
            End Set
        End Property
        
        Public ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("home", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property lebewesen() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("lebewesen", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property matrixback() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("matrixback", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property matrixback1() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("matrixback1", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property spielfelder() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("spielfelder", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("water", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Welten() As System.Drawing.Bitmap
            Get
                Return CType(ResourceManager.GetObject("Welten", _resCulture),System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
